# Step 1: Build
FROM node:16-alpine3.17 AS build-stage
WORKDIR /app
RUN chmod 777 /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Step 2: Production
FROM nginx:1.9.9
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]


